<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Rebot 6.0.1 (Python 3.10.4 on win32)" generated="20230612 13:59:13.103" rpa="false" schemaversion="3">
<suite id="s1" name="Main" source="G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main\Main.robot">
<test id="s1-t1" name="1 - Executes Main flow" line="6">
<kw name="When user runs main flow">
<msg timestamp="20230612 13:59:12.684" level="FAIL">No keyword with name 'When user runs main flow' found.</msg>
<status status="FAIL" starttime="20230612 13:59:12.682" endtime="20230612 13:59:12.684"/>
</kw>
<doc>Executes main flow</doc>
<tag>flow</tag>
<status status="FAIL" starttime="20230612 13:59:12.679" endtime="20230612 13:59:12.684">No keyword with name 'When user runs main flow' found.</status>
</test>
<doc>[https://pabot.org/?ref=log|Pabot] result from 1 executions.</doc>
<status status="FAIL" starttime="20230612 13:59:07.772" endtime="20230612 13:59:12.686"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">flow</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Main">Main</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230612 13:59:09.027" level="WARN">Imported library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\TransactionFormula.py' contains no keywords.</msg>
<msg timestamp="20230612 13:59:12.676" level="ERROR">Error in file 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main\Main.robot' on line 3: Importing library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py' failed: TypeError: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py", line 26, in &lt;module&gt;
    TEST_URL_LLT = PROTOCOL + TEST_URL
PYTHONPATH:
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\git\ext\gitdb
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  G:\Other computers\My Laptop\GDrive\talentbook\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms</msg>
</errors>
</robot>
