<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Rebot 6.0.1 (Python 3.10.4 on win32)" generated="20230616 19:16:23.986" rpa="false" schemaversion="3">
<suite id="s1" name="restAPI" source="G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI">
<kw name="Setup before all tests" type="SETUP">
<msg timestamp="20230616 19:16:18.401" level="TRACE">Arguments: [  ]</msg>
<kw name="Evaluate" library="BuiltIn">
<arg>sys.path.append(os.path.abspath('.'))</arg>
<arg>modules=os, sys</arg>
<doc>Evaluates the given expression in Python and returns the result.</doc>
<msg timestamp="20230616 19:16:18.404" level="TRACE">Arguments: [ "sys.path.append(os.path.abspath('.'))" | modules='os, sys' ]</msg>
<msg timestamp="20230616 19:16:18.404" level="TRACE">Return: None</msg>
<status status="PASS" starttime="20230616 19:16:18.402" endtime="20230616 19:16:18.404"/>
</kw>
<msg timestamp="20230616 19:16:18.404" level="TRACE">Return: None</msg>
<status status="PASS" starttime="20230616 19:16:18.399" endtime="20230616 19:16:18.404"/>
</kw>
<suite id="s1-s1" name="Main" source="G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main">
<suite id="s1-s1-s1" name="Main GPT v0 1" source="G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main\Main_GPT_v0_1.robot">
<test id="s1-s1-s1-t1" name="1 - Executes Main flow" line="6">
<kw name="When user runs main gpt flow">
<msg timestamp="20230616 19:16:23.524" level="FAIL">No keyword with name 'When user runs main gpt flow' found.</msg>
<status status="FAIL" starttime="20230616 19:16:23.521" endtime="20230616 19:16:23.524"/>
</kw>
<doc>Executes main flow</doc>
<tag>flow</tag>
<status status="FAIL" starttime="20230616 19:16:23.519" endtime="20230616 19:16:23.525">No keyword with name 'When user runs main gpt flow' found.</status>
</test>
<status status="FAIL" starttime="20230616 19:16:18.409" endtime="20230616 19:16:23.526"/>
</suite>
<status status="FAIL" starttime="20230616 19:16:18.404" endtime="20230616 19:16:23.528"/>
</suite>
<doc>[https://pabot.org/?ref=log|Pabot] result from 1 executions.</doc>
<status status="FAIL" starttime="20230616 19:16:18.373" endtime="20230616 19:16:23.529"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">flow</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="restAPI">restAPI</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Main">restAPI.Main</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Main GPT v0 1">restAPI.Main.Main GPT v0 1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230616 19:16:18.857" level="ERROR">Error in file 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\common.robot' on line 2: Importing library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Common\TokenAccess.py' failed: KeyError: 'PREPROD'
Traceback (most recent call last):
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Common\TokenAccess.py", line 9, in &lt;module&gt;
    from resources.restAPI.Common.RefererSession import RefererSession
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\__init__.py", line 7, in &lt;module&gt;
    ENV_DETAILS = YamlDataManipulator.YamlDataManipulator().user_retrieves_data_from_yaml("loginCredential.yaml",
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\setup\yaml\YamlDataManipulator.py", line 14, in user_retrieves_data_from_yaml
    return respond[data]
PYTHONPATH:
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Common
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  G:\Other computers\My Laptop\GDrive\talentbook\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms</msg>
<msg timestamp="20230616 19:16:18.933" level="WARN">Imported library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\TransactionFormula.py' contains no keywords.</msg>
<msg timestamp="20230616 19:16:23.517" level="ERROR">Error in file 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main\Main_GPT_v0_1.robot' on line 3: Importing library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main_GPT_v0_1.py' failed: KeyError: 'PREPROD'
Traceback (most recent call last):
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main_GPT_v0_1.py", line 14, in &lt;module&gt;
    from resources.restAPI import LLT_URL, PROTOCOL, GMAPS_TOKEN
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\__init__.py", line 7, in &lt;module&gt;
    ENV_DETAILS = YamlDataManipulator.YamlDataManipulator().user_retrieves_data_from_yaml("loginCredential.yaml",
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\setup\yaml\YamlDataManipulator.py", line 14, in user_retrieves_data_from_yaml
    return respond[data]
PYTHONPATH:
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\git\ext\gitdb
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\Scripts\robot.exe
  G:\Other computers\My Laptop\GDrive\talentbook\sherlock-dms
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\python310.zip
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\DLLs
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
  C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms
  G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms</msg>
</errors>
</robot>
