<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Rebot 6.0.1 (Python 3.10.4 on win32)" generated="20230518 14:14:55.153" rpa="false" schemaversion="3">
<suite id="s1" name="Main" source="G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\tests\restAPI\Main\Main.robot">
<test id="s1-t1" name="1 - Executes Main flow" line="6">
<kw name="When user runs main flow" library="Main">
<msg timestamp="20230518 14:14:44.467" level="TRACE">Arguments: [  ]</msg>
<msg timestamp="20230518 14:14:44.471" level="DEBUG">Starting new HTTPS connection (1): www.lelongtips.com.my:443</msg>
<msg timestamp="20230518 14:14:45.818" level="DEBUG">https://www.lelongtips.com.my:443 "GET /search?keyword=&amp;property_type%5B%5D=1&amp;property_type%5B%5D=4&amp;property_type%5B%5D=5&amp;property_type%5B%5D=3&amp;state=kl_sel&amp;min_price=150000&amp;max_price=1000000&amp;min_size=&amp;max_size=&amp;sort=price-asc&amp;listing_status=upcoming&amp;page=1 HTTP/1.1" 200 None</msg>
<msg timestamp="20230518 14:14:45.823" level="DEBUG">Starting new HTTPS connection (1): www.lelongtips.com.my:443</msg>
<msg timestamp="20230518 14:14:46.644" level="DEBUG">https://www.lelongtips.com.my:443 "GET /search?keyword=&amp;property_type%5B%5D=1&amp;property_type%5B%5D=4&amp;property_type%5B%5D=5&amp;property_type%5B%5D=3&amp;state=kl_sel&amp;min_price=150000&amp;max_price=1000000&amp;min_size=&amp;max_size=&amp;sort=price-asc&amp;listing_status=upcoming&amp;page=1 HTTP/1.1" 200 None</msg>
<msg timestamp="20230518 14:14:54.803" level="INFO">now i am at page 1
size of content_list= 12
size of draft_content= 0</msg>
<msg timestamp="20230518 14:14:54.803" level="INFO">G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py:524: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 524 of the file G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  parsed_html = BeautifulSoup(body_text)</msg>
<msg timestamp="20230518 14:14:54.804" level="FAIL">AttributeError: 'str' object has no attribute 'get_name'</msg>
<msg timestamp="20230518 14:14:54.818" level="DEBUG">Traceback (most recent call last):
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py", line 39, in user_runs_main_flow
    self.map_gen(draft_content)
  File "G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\restAPI\Main\Main.py", line 250, in map_gen
    m.get_root().html.add_child(html)
  File "C:\Users\r.a.ling\AppData\Local\Programs\Python\Python310\lib\site-packages\branca\element.py", line 123, in add_child
    name = child.get_name()
AttributeError: 'str' object has no attribute 'get_name'</msg>
<status status="FAIL" starttime="20230518 14:14:44.466" endtime="20230518 14:14:54.819"/>
</kw>
<doc>Executes main flow</doc>
<tag>flow</tag>
<status status="FAIL" starttime="20230518 14:14:44.465" endtime="20230518 14:14:54.819">AttributeError: 'str' object has no attribute 'get_name'</status>
</test>
<doc>[https://pabot.org/?ref=log|Pabot] result from 1 executions.</doc>
<status status="FAIL" starttime="20230518 14:14:40.782" endtime="20230518 14:14:54.821"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">flow</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Main">Main</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230518 14:14:41.463" level="WARN">Imported library 'G:\My Drive\Python\Scraper\Lelongtips\sherlock-dms\resources\TransactionFormula.py' contains no keywords.</msg>
</errors>
</robot>
